/** Install and boot the exact official Desktop runtime in a disposable web profile. */
import fs from 'node:fs/promises';import path from 'node:path';import {tmpdir} from 'node:os';import {spawn,execFile} from 'node:child_process';import {promisify} from 'node:util';import {pathToFileURL} from 'node:url';import assert from 'node:assert/strict';
const execute=promisify(execFile);
const app=process.env.DSH_BASH_TEST_APP||'D:/Code/DeepSeek Harness/DeepSeek Harness.exe',cli=process.env.DSH_BASH_TEST_CLI||path.join(path.dirname(app),'resources/app.asar/dsh/node_modules/@deepseek-ai/dsh-desktop-host/lib/cli.js');
const sshIndex=process.argv.indexOf('--ssh-package');if(sshIndex<0||!process.argv[sshIndex+1])throw new Error('Pass --ssh-package with the packed SSH plugin path');const sshPackage=path.resolve(process.argv[sshIndex+1]);
const root=await fs.mkdtemp(path.join(tmpdir(),'dsh-bash-host-'));await fs.mkdir('.tmp',{recursive:true});
const env=Object.fromEntries(Object.entries(process.env).filter(([key])=>!/(TOKEN|SECRET|PASSWORD|CREDENTIAL|API.?KEY)/i.test(key)&&!/^DSH_/i.test(key)));
Object.assign(env,{DSH_HOME:root,DSH_AGENTS_HOME:path.join(root,'agents'),ELECTRON_RUN_AS_NODE:'1'});let child,browser;
try{
 const version=JSON.parse(await fs.readFile('package.json','utf8')).version,archive=path.resolve('.tmp/very12345-dsh-bash-windows-'+version+'.tgz');
 const installed=await execute(app,['--expose-internals',cli,'plugin','--profile','web','add','file:'+archive.replaceAll('\\','/'),'--ignore-scripts'],{env,windowsHide:true,timeout:90000,maxBuffer:4*1024*1024});await fs.writeFile('.tmp/isolated-host-install.log',installed.stdout+installed.stderr);
 await execute(app,['--expose-internals',cli,'plugin','--profile','web','add','file:'+sshPackage.replaceAll('\\','/'),'--ignore-scripts'],{env,windowsHide:true,timeout:90000,maxBuffer:4*1024*1024});
 child=spawn(app,['--expose-internals',cli,'web','--port','0','--no-open'],{env,windowsHide:true,stdio:['ignore','pipe','pipe']});let output='';const capture=chunk=>{output=(output+String(chunk)).slice(-200000);};child.stdout.on('data',capture);child.stderr.on('data',capture);
 const deadline=Date.now()+30000;let base,catalog,uiUrl;
 while(Date.now()<deadline){
  if(child.exitCode!==null){await fs.writeFile('.tmp/isolated-host-start.log',output);throw new Error('Official test host exited before readiness');}
  const match=output.match(/https?:\/\/(?:127\.0\.0\.1|localhost):\d+[^\s\x1b]*/);if(match){const url=new URL(match[0].replace(/[),.;]+$/,''));base=url.origin;uiUrl=url.href;try{const response=await fetch(base+'/plugins/git-bash-windows');if(response.ok){const data=await response.json();if(data.ok){catalog=data;break;}}}catch{}}
  await new Promise(resolve=>setTimeout(resolve,100));
 }
 if(!catalog){await fs.writeFile('.tmp/isolated-host-start.log',output);throw new Error('Bash switch did not become active in the isolated official host');}
 const {chromium}=await import(process.env.DSH_BASH_PLAYWRIGHT_MODULE?pathToFileURL(process.env.DSH_BASH_PLAYWRIGHT_MODULE).href:'playwright');browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:1400,height:1000},locale:'zh-CN'});page.setDefaultTimeout(15000);const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',message=>{if(message.type()==='error')errors.push(message.text().slice(0,500));});await page.goto(uiUrl);await page.getByRole('button',{name:'设置',exact:true}).waitFor();const welcome=page.getByRole('dialog').filter({hasText:'预览版说明'});await welcome.waitFor();await welcome.getByRole('button',{name:'继续',exact:true}).click();await welcome.waitFor({state:'hidden'});const defer=page.getByRole('button',{name:'稍后配置',exact:true});await defer.waitFor();await defer.click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.waitForTimeout(400);const input=page.locator('textarea,[contenteditable=true]').first();await input.fill('/');await page.waitForTimeout(800);await page.keyboard.press('Escape');await input.fill('');await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByRole('button',{name:'Git Bash',exact:true}).click();const profileBefore=await fs.readFile(path.join(root,'profiles/web/cordis.patch.yml'),'utf8');console.log('pre-toggle',await (await fetch(base+'/plugins/git-bash-windows')).json());await page.getByRole('switch').click();await page.waitForTimeout(500);console.log('post-toggle',await (await fetch(base+'/plugins/git-bash-windows')).json());await page.keyboard.press('Escape');await input.fill('/');await page.waitForTimeout(1000);assert.equal(await fs.readFile(path.join(root,'profiles/web/cordis.patch.yml'),'utf8'),profileBefore);await page.keyboard.press('Escape');await input.fill('/model');await page.keyboard.press('Enter');await page.waitForTimeout(500);assert.ok((await page.locator('body').innerText()).includes('DeepSeek-V4-Pro'),'Model directory RPC remains available');console.log('post-toggle errors',errors);assert.ok(!errors.some(error=>error.includes('sessionController')||error.includes('command directory warmup')));await page.keyboard.press('Escape');await input.fill('');for(const enabled of [false,true,false]){const result=await (await fetch(base+'/plugins/git-bash-windows',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled})})).json();assert.equal(result.ok,true,JSON.stringify(result));assert.equal(result.enabled,enabled);assert.equal(await fs.readFile(path.join(root,'profiles/web/cordis.patch.yml'),'utf8'),profileBefore);}console.log('Three extra switches and unchanged profile document PASS');console.log('alerts',(await page.locator('[role=alert]').allTextContents()).map(x=>x.slice(0,250)));await fs.mkdir('.tmp/ui',{recursive:true});await page.screenshot({path:'.tmp/ui/bash-toggle.png'});await fs.writeFile('.tmp/bash-host-output.log',output);
 console.log('Official DSH + SSH: unchanged profile, four live Bash switches, command warmup and model directory RPC PASS');
}finally{await browser?.close();if(child&&child.exitCode===null){child.kill();await new Promise(resolve=>child.once('exit',resolve));}await fs.rm(root,{recursive:true,force:true,maxRetries:10,retryDelay:100});}
