import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import {tmpdir} from 'node:os';import {SwitchPreferences} from '../src/preferences.js';
test('independent profile preferences survive restart and leave the profile document unchanged',async t=>{
 const home=await fs.mkdtemp(path.join(tmpdir(),'bash-state-'));t.after(()=>fs.rm(home,{recursive:true,force:true}));const profile={home,dir:path.join(home,'profiles/desktop')};await fs.mkdir(profile.dir,{recursive:true});const document=path.join(profile.dir,'cordis.patch.yml');await fs.writeFile(document,'- id: git-bash-windows\n  config: { enabled: true }\n');const before=await fs.readFile(document),store=new SwitchPreferences(profile);assert.equal(await store.load(),undefined);await assert.rejects(fs.stat(store.directory),/ENOENT/);await store.save(false);assert.equal(await new SwitchPreferences(profile).load(),false);await store.save(true);assert.equal(await new SwitchPreferences(profile).load(),true);assert.equal(await new SwitchPreferences({home,dir:path.join(home,'profiles/web')}).load(),undefined);assert.deepEqual(await fs.readFile(document),before);assert.deepEqual((await fs.readdir(store.directory)).filter(name=>name.endsWith('.tmp')),[]);
});
test('invalid and linked preference targets are rejected without changing external files',async t=>{
 const home=await fs.mkdtemp(path.join(tmpdir(),'bash-state-boundary-'));t.after(()=>fs.rm(home,{recursive:true,force:true}));const store=new SwitchPreferences({home,dir:path.join(home,'profiles/desktop')});await store.save(false);await fs.writeFile(store.path,'{"version":1,"enabled":"yes"}');await assert.rejects(store.load(),/invalid/);await fs.unlink(store.path);await fs.rmdir(store.directory);const outside=path.join(home,'outside');await fs.mkdir(outside);await fs.symlink(outside,store.directory,process.platform==='win32'?'junction':'dir');await assert.rejects(store.save(true),/plain directory/);assert.deepEqual(await fs.readdir(outside),[]);
});
test('failed persistence rolls back the shell switch and never calls host settings update',async t=>{
 let Context,GitBashSwitcher;try{({Context}=await import('@deepseek-ai/cordis'));({GitBashSwitcher}=await import('../src/switcher.js'));}catch(error){t.skip(error.message);return;}
 const ctx=new Context();ctx.provide('agents',{list:()=>[]});ctx.provide('agentPresets',{composedPreset:()=>undefined});ctx.provide('settings',{configure:()=>()=>{},update:()=>{throw new Error('Host config edit forbidden');}});const controller=new GitBashSwitcher(ctx,{enabled:false},{async load(){return undefined;},async save(){throw new Error('Owned file write failed');}});await controller.pending;t.after(()=>ctx.fiber.dispose());await assert.rejects(controller.setEnabled(true),/Owned file write failed/);assert.equal(controller.enabled,false);
});
